columns:
  - PCOS (Y/N): int64
  - Age (yrs): int64
  - Weight (Kg): float
  - Height(Cm): float
  - BMI: float
  - Blood Group: int64
  - Pulse rate(bpm): int64
  - RR (breaths/min): int64
  - Hb(g/dl): float
  - Cycle(R/I): int64
  - Cycle length(days): int64
  - Marraige Status (Yrs): float
  - Pregnant(Y/N): int64
  - No. of aborptions: int64
  - I beta-HCG(mIU/mL): float
  - II beta-HCG(mIU/mL): float
  - FSH(mIU/mL): float
  - LH(mIU/mL): float
  - FSH/LH: float
  - Hip(inch): int64
  - Waist(inch): int64
  - Waist:Hip Ratio: float
  - TSH (mIU/L): float
  - AMH(ng/mL): float
  - PRL(ng/mL): float
  - Vit D3 (ng/mL): float
  - PRG(ng/mL): float
  - RBS(mg/dl): float
  - Weight gain(Y/N): int64
  - hair growth(Y/N): int64
  - Skin darkening (Y/N): int64
  - Hair loss(Y/N): int64
  - Pimples(Y/N): int64
  - Fast food (Y/N): float
  - Reg.Exercise(Y/N): int64
  - BP _Systolic (mmHg): int64
  - BP _Diastolic (mmHg): int64
  - Follicle No. (L): int64
  - Follicle No. (R): int64
  - Avg. F size (L) (mm): float
  - Avg. F size (R) (mm): float
  - Endometrium (mm): float

numerical_columns:
  - PCOS (Y/N)
  - Age (yrs)
  - Weight (Kg)
  - Height(Cm)
  - BMI
  - Blood Group
  - Pulse rate(bpm)
  - RR (breaths/min)
  - Hb(g/dl)
  - Cycle(R/I)
  - Cycle length(days)
  - Marraige Status (Yrs)
  - Pregnant(Y/N)
  - No. of aborptions
  - I beta-HCG(mIU/mL)
  - II beta-HCG(mIU/mL)
  - FSH(mIU/mL)
  - LH(mIU/mL)
  - FSH/LH
  - Hip(inch)
  - Waist(inch)
  - Waist:Hip Ratio
  - TSH (mIU/L)
  - AMH(ng/mL)
  - PRL(ng/mL)
  - Vit D3 (ng/mL)
  - PRG(ng/mL)
  - RBS(mg/dl)
  - Weight gain(Y/N)
  - hair growth(Y/N)
  - Skin darkening (Y/N)
  - Hair loss(Y/N)
  - Pimples(Y/N)
  - Fast food (Y/N)
  - Reg.Exercise(Y/N)
  - BP _Systolic (mmHg)
  - BP _Diastolic (mmHg)
  - Follicle No. (L)
  - Follicle No. (R)
  - Avg. F size (L) (mm)
  - Avg. F size (R) (mm)
  - Endometrium (mm)

